# Generated by Django 5.2 on 2026-09-23 00:00
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="categories/%Y/%m/%d/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["is_active", "name"], name="store_categor_is_act_1b0a76_idx")],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="store.category")),
            ],
            options={
                "ordering": ["-featured", "-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "featured"], name="store_produc_is_act_0c14d4_idx"),
                    models.Index(fields=["category", "is_active"], name="store_produc_categor_44d6df_idx"),
                    models.Index(fields=["name"], name="store_produc_name_84b8fe_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="products/%Y/%m/%d/")),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.product")),
            ],
            options={"ordering": ["-is_primary", "created_at"]},
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("size", models.CharField(choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL"), ("XXL", "XXL"), ("28", "28"), ("30", "30"), ("32", "32"), ("34", "34"), ("36", "36"), ("38", "38"), ("40", "40"), ("42", "42")], max_length=8)),
                ("color", models.CharField(choices=[("BLACK", "Black"), ("NAVY", "Navy"), ("BLUE", "Blue"), ("LIGHT_BLUE", "Light Blue"), ("WHITE", "White"), ("GRAY", "Gray"), ("CHARCOAL", "Charcoal"), ("GREEN", "Green"), ("OLIVE", "Olive"), ("RED", "Red"), ("BEIGE", "Beige"), ("BROWN", "Brown")], max_length=30)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("sku", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="store.product")),
            ],
            options={
                "ordering": ["product", "size", "color"],
                "indexes": [models.Index(fields=["product", "stock"], name="store_produc_product_3f7c42_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(fields=("product", "size", "color"), name="unique_variant_per_product_size_color"),
        ),
    ]
