# Generated by Django 5.2.17 on 2026-09-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='store_categ_is_acti_a5969f_idx',
            old_name='store_categor_is_act_1b0a76_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_is_acti_8f1d25_idx',
            old_name='store_produc_is_act_0c14d4_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_categor_591340_idx',
            old_name='store_produc_categor_44d6df_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_name_5e57da_idx',
            old_name='store_produc_name_84b8fe_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='store_produ_product_529289_idx',
            old_name='store_produc_product_3f7c42_idx',
        ),
    ]
