# Generated by Django 5.2.17 on 2026-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0002_rename_store_categor_is_act_1b0a76_idx_store_categ_is_acti_a5969f_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_item_quantity_gte_one'),
        ),
    ]
